name: CI

on:
  merge_group:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, canary]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  PUBLIC_SANITY_DATASET: ${{ vars.PUBLIC_SANITY_DATASET }}
  PUBLIC_SANITY_PROJECT_ID: ${{ vars.PUBLIC_SANITY_PROJECT_ID }}
  PUBLIC_SANITY_STUDIO_URL: ${{ vars.PUBLIC_SANITY_STUDIO_URL }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN || 'placeholder' }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint

  build-and-check:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN || 'placeholder' }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm build:packages
      - run: pnpm check:packages
